name: Run Telegram Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  bot-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install aiogram

      - name: Run bot
        env:
          BOT_TOKEN6767: ${{ secrets.BOT_TOKEN6767 }}
        run: |
          python main.py
